#!/bin/bash

# Repositorios
got="https://github.com/zsh4k/got"
git="https://github.com/zsh4k/nowya-git"
nodejs="https://github.com/zsh4k/nowya-nodejs"
docker="https://github.com/zsh4k/nowya-docker"
lua="https://github.com/zsh4k/nowya-lua"
php="https://github.com/zsh4k/nowya-php"

# Función para instalar
function install_nya {
    curl -s "$1" | grep "<code>" | sed 's/^.*<code>//;s/<\/code>.*$//;s/&amp;/\&/g' | head -n 1 | bash
}

# Argumentos
for arg in "$@"; do
    if [ "$arg" = "got" ]; then
        install_nya $got
    elif [ "$arg" = "git" ]; then
        install_nya $git
    elif [ "$arg" = "nodejs" ]; then
        install_nya $nodejs
    elif [ "$arg" = "docker" ]; then
        install_nya $docker
    elif [ "$arg" = "lua" ]; then
        install_nya $lua
    elif [ "$arg" = "php" ]; then
        install_nya $php
    fi
done