#!/bin/bash

got="cd /usr/bin && wget https://raw.githubusercontent.com/zsh4k/got/main/got && chmod +x got && cd"
nodejs="wget https://raw.githubusercontent.com/zsh4k/nodeinstaller/main/index.sh && mkdir go.files && cd go.files && wget https://github.com/zsh4k/nodeinstaller/raw/main/go.files/get.last.version && cd .. && chmod +x ./index.sh && source ./index.sh && reboot"
docker="cd /usr/bin && wget https://raw.githubusercontent.com/zsh4k/nowya-docker/main/nowya-docker && chmod +x nowya-docker && cd && nowya-docker"


for arg in "$@"; do
    if [ "$arg" = "got" ]; then
        eval $got
    elif [ "$arg" = "nodejs" ]; then
        eval $nodejs
    elif [ "$arg" = "docker" ]; then
        eval $docker
    fi
done
